name: Check File Size
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-large-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # 10MB
